---
AWSTemplateFormatVersion: 2010-09-09
Description: Resources to operate asg-node-refresh

Resources:
  clusterAutoScalerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: asg-node-refresh-<< .config.clusterName >>
      Path: /k8s/<< .config.clusterName >>/kubesystem/
      AssumeRolePolicyDocument:
        Fn::Sub:
          - |
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "sts:AssumeRoleWithWebIdentity"
                        ],
                        "Principal": {
                            "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.${AWS::Region}.amazonaws.com/id/${id}"
                        },
                        "Condition": {
                            "StringEquals": {
                                "oidc.eks.${AWS::Region}.amazonaws.com/id/${id}:sub": "system:serviceaccount:kube-system:asg-node-refresh"
                            }
                        }
                    }
                ]
            }
          -
            id:
              Fn::Select:
                - 1
                - Fn::Split:
                    - "//"
                    - Fn::Select:
                        - 0
                        - Fn::Split:
                            - "."
                            - Fn::ImportValue: EksCluster-Endpoint-<< .config.clusterName >>
      Policies:
        - PolicyName: access-to-asg
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "autoscaling:*"
                  - "ec2:*"
                Resource: "*"
