---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asg-node-roller
  namespace: kube-system
  labels:
    repo: asg-node-roller
    addon: asg-node-roller
spec:
  replicas: 1
  selector:
    matchLabels:
      repo: asg-node-roller
      addon: asg-node-roller
  template:
    metadata:
      labels:
        repo: asg-node-roller
        addon: asg-node-roller
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
    spec:
      serviceAccountName: asg-node-roller
      containers:
        - name: asg-node-roller
          imagePullPolicy: IfNotPresent
          image: ikerry/asg-node-roller:<< .config.asgNodeRoller.version >>
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: AWS_DEFAULT_REGION
              value: << .config.region >>
            - name: AWS_REGION
              value: << .config.region >>
            - name: "LOG_LEVEL"
              value: "info"
