---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: asg-node-roller-role
  labels:
    repo: asg-node-roller
    addon: asg-node-roller
rules:
  - apiGroups:
      - ""
    resources:
      - componentstatuses
      - events
      - namespaces
      - persistentvolumes
      - resourcequotas
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - *
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - get
      - list
      - watch
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: asg-node-roller-rolebinding
  labels:
    repo: asg-node-roller
    addon: asg-node-roller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: asg-node-roller-role
subjects:
  - kind: ServiceAccount
    name: asg-node-roller
    namespace: kube-system
