---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: asg-node-roller-role
  labels:
    repo: asg-node-roller
    addon: asg-node-roller
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "*"
    resources:
      - nodes
      - pods
      - pods/eviction
    verbs:
      - *

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: asg-node-roller-rolebinding
  labels:
    repo: asg-node-roller
    addon: asg-node-roller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: asg-node-roller-role
subjects:
  - kind: ServiceAccount
    name: asg-node-roller
    namespace: kube-system
