---
AWSTemplateFormatVersion: 2010-09-09
Description: Resources to operate asg-node-roller
Resources:
  clusterAutoScalerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: asg-node-roller-<< .config.clusterName >>
      Path: /k8s/<< .config.clusterName >>/kubesystem/
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: arn:aws:iam::<< .config.aws.accountId >>:oidc-provider/oidc.eks.<< .config.aws.region >>.amazonaws.com/id/<< .config.aws.clusterId >>
            Condition:
              StringEquals:
                oidc.eks.<< .config.aws.region >>.amazonaws.com/id/<< .config.aws.clusterId >>:sub: system:serviceaccount:kube-system:asg-node-roller
      Policies:
        - PolicyName: access-to-asg
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "autoscaling:*"
                  - "ec2:*"
                Resource: "*"
